version: "3.8"

services:

  tracking-app:
    build: .
    container_name: tracking-app
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - redis
      - mongodb
    networks:
      - tracking-network
    environment:
      SPRING_PROFILES_ACTIVE: docker