version: "3.8"

services:
  tracking-app:
    build:
      context: . # Kendi klasöründeki Dockerfile'ı kullanır
    container_name: tracking-app-standalone
    ports:
      - "8081:8081"
    networks:
      - tracking-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # 🚀 Eğer bu bağımsız dosyayı çalıştırırsanız, bilgisayarınızda kurulu olan (localhost) servisleri arar:
      - spring.data.redis.host=localhost
      - spring.data.mongodb.host=localhost
      - spring.kafka.bootstrap-servers=localhost:9092

networks:
  tracking-network:
    driver: bridge
