server:
  port: 8081

spring:
  application:
    name: tracking-service

  data:
    redis:
      host: redis-local
      port: 6379
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 4
          max-wait: 2000ms

    mongodb:
      uri: mongodb://mongodb-local:27017/tracking

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka-local:29092}
    consumer:
      auto-offset-reset: earliest
