server:
  port: 8081

spring:
  application:
    name: tracking-service

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis} # <-- Değişti
      port: 6379
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 4
          max-wait: 2000ms

    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/tracking} # <-- Değişti

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092} # <-- Değişti
    consumer:
      auto-offset-reset: earliest

