spring:
  application:
    name: tracking

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

application:
  jwt:
    secret-key: ${APPLICATION_JWT_SECRET_KEY}